(source gnu)
(source melpa)

(package-file "symex-ide.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "package-lint")
 (depends-on "flycheck"))
